trigger:
- main
steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'local-sq'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'sonar-swaggerator'
    cliProjectName: 'sonar-swaggerator'
    cliSources: '.'
- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'